ANTOURA/Controllers/AgendaController.cs
using ANTOURA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ANTOURA.Controllers
{
    public class AgendaController : BaseController
    {
        private AgendaRepository rpstry = new AgendaRepository();

        public ActionResult Index() {
            var recordsToReturn = rpstry.GetAll();
            return View(recordsToReturn);
        }

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Agenda entry)
        {
            try
            {
                entry.dateCreated = DateTime.Now;
                entry.dateModified = DateTime.Now;
                rpstry.Add(entry);
                rpstry.Save();
                return RedirectToAction("Index", new { thisid = entry.id });
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "");
                return View(entry);
            }
        }
        #endregion
        #region Edit
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var entry = rpstry.GetById(id);
            return View(entry);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection coll)
        {
            var entry = rpstry.GetById(id);
            try
            {
                UpdateModel(entry);

                entry.dateModified = DateTime.Now;
                rpstry.Save();
                return RedirectToAction("Index", new { thisid = entry.id });
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "");
                return View(entry);
            }
        }
        #endregion

        public ActionResult Delete(int id) {
            var entry = rpstry.GetById(id);
            rpstry.Delete(entry);
            rpstry.Save();
            return RedirectToAction("Index");
        }

    }
}

ANTOURA/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>

    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            var icons = {
                header: "defaultIcon",
                activeHeader: "selectedIcon"
            };
            $("#accordion").accordion({ icons: icons, collapsible: true });


        });
    </script>
</head>

<body>
  
    <!-- wrapper -->
    <div class="wrapper">
        <!-- HEADER -->
        <header class="mainheader">
            <div class="logosis"> <img src="@Url.Content("~/content/images/SIS LOGO.png")" /> </div>

            <a href="www.college-antoura.edu.lb" class="logoantoura">
                <img src="@Url.Content("~/content/images/ANTOURA LOGO.png")" />
            </a>

            <div class="language">EN - FR </div>
        </header>
        <!-- END HEADER -->


        <div class="content">

            <div class="leftcontent">
                <div class="class">
                    <div id="accordion">
                        <h3>CLASSE</h3>
                        <p>
                            6A
                        </p>
                      
                    </div>
                </div>
            </div>

            <div class="rightcontent">
                @{Html.RenderPartial("_Welcome");}
               <div class="hr1">
                   
               </div>
                <div class="hr2">

                </div>
                <nav class="nav1">
    <ul id="menu">
        <li>@Html.ActionLink("AGENDA", "index", "Agenda")</li>
        <li>|</li>
        <li>@Html.ActionLink("CONTROLE", "Index", "Examen")</li>
        <li>|</li>
        <li>@Html.ActionLink("LIVRET", "Contact", "Home")</li>
        
    </ul>
</nav>
                
                    @RenderBody()
                
                   
              

            </div>



        </div>

    </div>

    @RenderSection("Scripts", required: false)

</body>
@*<body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>*@

</html>

ANTOURA/Views/Shared/_Welcome.cshtml
@{
    var controller = ViewContext.RouteData.Values["controller"].ToString().ToLower();
    var action = ViewContext.RouteData.Values["action"].ToString().ToLower();
    var loggedUser = (ANTOURA.Models.webpages_Membership)ViewBag.LoggedUser;
}

<div class="welcome">
    Bienvenue, @(loggedUser.FirstName + " " + loggedUser.LastName ) | 
</div>
<div>
    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
    {@Html.AntiForgeryToken()


        <a class="welcomea" href="javascript:document.getElementById('logoutForm').submit()">SIGN OUT</a>

    }
</div>